interface InterfaceVacancy {
  id: string,
  title: string,
  describe: string,
  salary: string,
  date: string,
  currency: 'dollar' | 'euro' | 'uan',
  available: boolean,
  city: 'lviv' | 'kiev' | 'kharkiv',
  category: 'computer Science' | 'shop worker' | 'builder'
}

export const vacancies: InterfaceVacancy[] = [
  {
    id: '#%#!QSADF',
    title: 'IT junior',
    describe: 'developer 600$ salary, React, JS, SASS, HTML',
    salary: '600$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'kharkiv',
    category: 'computer Science'
  },
  {
    id: 'hertwjw',
    title: 'IT middle',
    describe: 'developer 1400$ salary, React, JS, SASS, HTML',
    salary: '1400$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'kharkiv',
    category: 'computer Science'
  },
  {
    id: 'adsgfdefsb',
    title: 'IT senior',
    describe: 'developer 6000$ salary, React, JS, SASS, HTML, NodeJS,',
    salary: '3600$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'kharkiv',
    category: 'computer Science'
  },
  {
    id: 'yjte435',
    title: 'IT middle',
    describe: 'developer 1400$ salary, React, JS, SASS, HTML',
    salary: '1400$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'kharkiv',
    category: 'computer Science'
  },
  {
    id: '3546xzgf',
    title: 'IT senior',
    describe: 'developer 6000$ salary, React, JS, SASS, HTML, NodeJS,',
    salary: '3600$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'kharkiv',
    category: 'computer Science'
  },
  {
    id: '1',
    title: 'IT junior',
    describe: 'developer 600$ salary, React, JS, SASS, HTML',
    salary: '600$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'lviv',
    category: 'computer Science'
  },
  {
    id: '2',
    title: 'IT middle',
    describe: 'developer 1400$ salary, React, JS, SASS, HTML',
    salary: '1400$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'lviv',
    category: 'computer Science'
  },
  {
    id: '3',
    title: 'IT senior',
    describe: 'developer 6000$ salary, React, JS, SASS, HTML, NodeJS,',
    salary: '3600$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'lviv',
    category: 'computer Science'
  },
  {
    id: '4',
    title: 'IT injener',
    describe: 'developer 6000$ salary, React, JS, SASS, HTML, Angular, NodeJS,',
    salary: '5000$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'lviv',
    category: 'computer Science'
  },
  {
    id: '5',
    title: 'IT Google developer',
    describe: 'developer 6000$ salary, React, JS, SASS, HTML, Angular, NodeJS, VueJs, PHP, C++',
    salary: '6000$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'lviv',
    category: 'shop worker'
  },
  {
    id: '6',
    title: 'Rozetka consultant 1',
    describe: 'lorem lorem lorem',
    salary: '400$',
    date: '21.04.2021',
    currency: 'dollar',
    available: true,
    city: 'lviv',
    category: 'shop worker'
  },
  {
    id: '7',
    title: 'Rozetka consultant 2',
    describe: 'lorem lorem lorem',
    salary: '200$',
    date: '21.04.2021',
    currency: 'dollar',
    available: true,
    city: 'lviv',
    category: 'computer Science'
  },
  {
    id: '8',
    title: 'Rozetka consultant 3',
    describe: 'lorem lorem lorem',
    salary: '300$',
    date: '21.04.2021', 
    currency: 'dollar',
    available: true,
    city: 'lviv',
    category: 'shop worker'
  },
  {
    id: '9',
    title: 'To do home with bricks',
    describe: 'lorem lorem lorem',
    salary: '900$',
    date: '21.04.1999',
    currency: 'dollar',
    available: true,
    city: 'lviv',
    category: 'builder'
  },
  {
    id: '812r',
    title: 'Rozetka consultant 3',
    describe: 'lorem lorem lorem',
    salary: '300$',
    date: '21.04.2021', 
    currency: 'dollar',
    available: true,
    city: 'kharkiv',
    category: 'shop worker'
  },
  {
    id: '9awf32',
    title: 'To do home with bricks',
    describe: 'lorem lorem lorem',
    salary: '900$',
    date: '21.04.1999',
    currency: 'dollar',
    available: true,
    city: 'kharkiv',
    category: 'builder'
  },
  {
    id: '10',
    title: 'To do home with bricks',
    describe: 'lorem lorem lorem',
    salary: '800$',
    date: '21.04.1941',
    currency: 'dollar',
    available: true,
    city: 'lviv',
    category: 'builder'
  },
  {
    id: '91241',
    title: 'To do home with bricks',
    describe: 'lorem lorem lorem',
    salary: '900$',
    date: '21.04.1999',
    currency: 'dollar',
    available: true,
    city: 'lviv',
    category: 'builder'
  },
  {
    id: '10345',
    title: 'To do home with bricks',
    describe: 'lorem lorem lorem',
    salary: '800$',
    date: '21.04.1941',
    currency: 'dollar',
    available: false,
    city: 'lviv',
    category: 'builder'
  },
  {
    id: '1032345',
    title: 'To do home with bricks',
    describe: 'lorem lorem lorem',
    salary: '1200$',
    date: '21.04.1941',
    currency: 'dollar',
    available: false,
    city: 'kiev',
    category: 'builder'
  },
  {
    id: '1032345A',
    title: 'To do home with bricks',
    describe: 'lorem lorem lorem',
    salary: '1200$',
    date: '21.04.1941',
    currency: 'dollar',
    available: false,
    city: 'kiev',
    category: 'builder'
  },
  {
    id: '10323453',
    title: 'To do home with bricks',
    describe: 'lorem lorem lorem',
    salary: '1200$',
    date: '21.04.1941',
    currency: 'dollar',
    available: false,
    city: 'kiev',
    category: 'builder'
  },
  {
    id: '10323452',
    title: 'To do home with bricks',
    describe: 'lorem lorem lorem',
    salary: '1200$',
    date: '21.04.1941',
    currency: 'dollar',
    available: false,
    city: 'kiev',
    category: 'builder'
  },
  {
    id: '10323451',
    title: 'To do home with bricks',
    describe: 'lorem lorem lorem',
    salary: '1200$',
    date: '21.04.1941',
    currency: 'dollar',
    available: false,
    city: 'kiev',
    category: 'builder'
  },
  {
    id: '10As3453',
    title: 'To do home with bricks',
    describe: 'lorem lorem lorem',
    salary: '1900$',
    date: '21.04.1941',
    currency: 'dollar',
    available: false,
    city: 'kharkiv',
    category: 'builder'
  },
  {
    id: '10asd3452',
    title: 'To do home with bricks',
    describe: 'lorem lorem lorem',
    salary: '1400$',
    date: '21.04.1941',
    currency: 'dollar',
    available: false,
    city: 'kharkiv',
    category: 'builder'
  },
  {
    id: '1032gf51',
    title: 'To do home with bricks',
    describe: 'lorem lorem lorem',
    salary: '1100$',
    date: '21.04.1941',
    currency: 'dollar',
    available: false,
    city: 'kharkiv',
    category: 'builder'
  },
  {
    id: '11',
    title: 'IT junior',
    describe: 'developer 600$ salary, React, JS, SASS, HTML',
    salary: '600$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'computer Science'
  },
  {
    id: '22',
    title: 'IT middle',
    describe: 'developer 1400$ salary, React, JS, SASS, HTML',
    salary: '1400$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'computer Science'
  },
  {
    id: '33',
    title: 'IT senior',
    describe: 'developer 6000$ salary, React, JS, SASS, HTML, NodeJS,',
    salary: '3600$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'computer Science'
  },
  {
    id: '141',
    title: 'IT junior',
    describe: 'developer 600$ salary, React, JS, SASS, HTML',
    salary: '600$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'computer Science'
  },
  {
    id: '122',
    title: 'IT middle',
    describe: 'developer 1400$ salary, React, JS, SASS, HTML',
    salary: '1400$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'computer Science'
  },
  {
    id: '3412',
    title: 'IT senior',
    describe: 'developer 6000$ salary, React, JS, SASS, HTML, NodeJS,',
    salary: '3600$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'computer Science'
  },
  {
    id: '12354',
    title: 'IT injener',
    describe: 'developer 6000$ salary, React, JS, SASS, HTML, Angular, NodeJS,',
    salary: '5000$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'computer Science'
  },
  {
    id: '523',
    title: 'IT Google developer',
    describe: 'developer 6000$ salary, React, JS, SASS, HTML, Angular, NodeJS, VueJs, PHP, C++',
    salary: '6000$',
    date: '31.01.2022',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'computer Science'
  },
  {
    id: '6as21',
    title: 'Rozetka consultant 1',
    describe: 'lorem lorem lorem',
    salary: '400$',
    date: '21.04.2021',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'shop worker'
  },
  {
    id: '7asdgf2',
    title: 'Rozetka consultant 2',
    describe: 'lorem lorem lorem',
    salary: '400$',
    date: '21.04.2021',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'shop worker'
  },
  {
    id: '8asf2',
    title: 'Rozetka consultant 3',
    describe: 'lorem lorem lorem',
    salary: '400$',
    date: '21.04.2021',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'shop worker'
    
  },
  {
    id: '6hsetr2',
    title: 'Rozetka consultant 1',
    describe: 'lorem lorem lorem',
    salary: '400$',
    date: '21.04.2021',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'shop worker'
  },
  {
    id: 'agdsgas45',
    title: 'Rozetka consultant 2',
    describe: 'lorem lorem lorem',
    salary: '400$',
    date: '21.04.2021',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'shop worker'
  },
  {
    id: 'bu32',
    title: 'Rozetka consultant 3',
    describe: 'lorem lorem lorem',
    salary: '400$',
    date: '21.04.2021',
    currency: 'dollar',
    available: true,
    city: 'kiev',
    category: 'shop worker'
  },

]